-- =====================================================================
-- DimCloud / DimDim - DDL das tabelas no Azure SQL Database (T-SQL)
-- Relacionamento: TB_CORRENTISTA (1) ---- (N) TB_TRANSACAO
-- =====================================================================

IF OBJECT_ID('dbo.TB_TRANSACAO', 'U') IS NOT NULL DROP TABLE dbo.TB_TRANSACAO;
IF OBJECT_ID('dbo.TB_CORRENTISTA', 'U') IS NOT NULL DROP TABLE dbo.TB_CORRENTISTA;
GO

CREATE TABLE dbo.TB_CORRENTISTA (
    ID_CORRENTISTA  BIGINT IDENTITY(1,1) NOT NULL,
    NOME            NVARCHAR(100)        NOT NULL,
    CPF             CHAR(11)             NOT NULL,
    EMAIL           NVARCHAR(120)        NOT NULL,
    TELEFONE        NVARCHAR(20)         NULL,
    DT_CADASTRO     DATETIME2(6)         NOT NULL CONSTRAINT DF_CORRENTISTA_DT DEFAULT SYSDATETIME(),
    CONSTRAINT PK_CORRENTISTA PRIMARY KEY (ID_CORRENTISTA),
    CONSTRAINT UK_CORRENTISTA_CPF UNIQUE (CPF)
);
GO

CREATE TABLE dbo.TB_TRANSACAO (
    ID_TRANSACAO    BIGINT IDENTITY(1,1) NOT NULL,
    ID_CORRENTISTA  BIGINT               NOT NULL,
    TIPO            VARCHAR(20)          NOT NULL,
    VALOR           DECIMAL(15,2)        NOT NULL,
    DESCRICAO       NVARCHAR(150)        NULL,
    DT_TRANSACAO    DATETIME2(6)         NOT NULL,
    CONSTRAINT PK_TRANSACAO PRIMARY KEY (ID_TRANSACAO),
    CONSTRAINT FK_TRANSACAO_CORRENTISTA FOREIGN KEY (ID_CORRENTISTA)
        REFERENCES dbo.TB_CORRENTISTA (ID_CORRENTISTA) ON DELETE CASCADE,
    CONSTRAINT CK_TRANSACAO_TIPO CHECK (TIPO IN ('DEPOSITO', 'SAQUE', 'PIX_ENVIADO', 'PIX_RECEBIDO')),
    CONSTRAINT CK_TRANSACAO_VALOR CHECK (VALOR > 0)
);
GO

CREATE INDEX IX_TRANSACAO_CORRENTISTA ON dbo.TB_TRANSACAO (ID_CORRENTISTA);
GO
